name: Deploy to DigitalOcean and AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DigitalOcean via SSH
        run: |
          echo "$DO_SSH_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ $DO_USER@$DO_HOST:/var/www/html/
        env:
          DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
          DO_USER: ${{ secrets.DO_USER }}
          DO_HOST: ${{ secrets.DO_HOST }}
